name: Update IPv4 Waitlist Data

on:
  schedule:
    - cron: '0 2 * * 3'  # Run weekly on Wednesdays at 02:00 UTC


  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-waitlist-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit changes back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run waitlist data collection
        run: |
          # Copy current waitlist_data.json as previous for comparison
          if [ -f data/waitlist_data.json ]; then
            cp data/waitlist_data.json data/previous_waitlist_data.json
          fi

          # Run process.py with previous file comparison
          if [ -f data/previous_waitlist_data.json ]; then
            python process.py --csv --no-header --previous-file data/previous_waitlist_data.json >> docs/waitlist_data.csv
          else
            python process.py --csv --no-header >> docs/waitlist_data.csv
          fi

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code docs/waitlist_data.csv data/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/waitlist_data.csv data/
          git commit -m "Update IPv4 waitlist data - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push

      - name: No changes detected
        if: steps.git-check.outputs.changes != 'true'
        run: |
          echo "No changes detected in waitlist data"